(* === BASIC CHARACTER DEFINITIONS === *)
CHAR = ? CHAR ?;

(* === BASIC VALUE TYPES === *)
true = "True" | "true" ;

false = "False" | "false" ;

boolean = true | false ;

(* === IDENTIFIERS === *)
identifier = ? identifier_name ? ;
quoted_identifier = ? escaped_string ? | identifier ;

(* === VALUE TYPES === *)
value_identifier = quoted_identifier ;
value_number = ? number ? ;
value_boolean = boolean ;
value = value_identifier | value_number | value_boolean ;

(* === ARGUMENTS === *)
arg_identifier_eq = quoted_identifier , "=" , value ;
arg_identifier_only = quoted_identifier ;
arg_number = ? number ? ;
arg_boolean = boolean ;
arg = arg_identifier_eq | arg_identifier_only | arg_number | arg_boolean ;
args = arg , { "," , arg } ;

(* === SEPARATOR DEFINITIONS === *)
SEPARATOR = ";" ;

(* === NEWLINE DEFINITIONS === *)
NEWLINES = NEWLINE , { NEWLINE } ;

(* === PROGRAM STRUCTURE === *)
    (* === PROGRAM COMPONENTS === *)

    (* === COMMENTS === *)
simple_comment = "#" , ? any_character_except_newline ? ;
multiline_comment = ? any_character_except_triple_quotes ? ;
comment = simple_comment | multiline_comment ;
comments = comment , { comment } ;

    (* === DECLARATION SECTION === *)
declaration_section = identifier , ":=" , value ;

    (* === PROPERTY SECTION === *)
logic_connection        = "AND" | "OR" ;

logic_operation     = "==" | "!=" | "<" | "<=" | ">" | ">=" ;

logic_expr   = [ "NOT" ] , identifier , logic_operation , value ;
logic_implication = "(" , logic_expr , "->" , logic_expr , ")" ;
logic_assertion   = logic_implication , { logic_connection , logic_implication } ;


function = ? official_functions ? ;
function_expr = function , "(" , [ args ] , ")" ;
problem_expr = ? official_problems ? , "." , function_expr ;

assertion = problem_expr | logic_assertion ;

    (* === PROPERTY EXPRESSION OPTIONS === *)
property_expr = universal_expr | anchor_expr | check_expr | pairwise_expr ;

quantifier = ? official_quantifier ? , [ identifier ] , "in" ;

    (* === UNIVERSAL EXPRESSIONS === *)
universal_set = ? official_sets ? , "(" , [ args ] , ")" ;
universal_expr = quantifier , universal_set ;

    (* === ANCHOR EXPRESSIONS === *)
domain = "with" , identifier , "(" , value , { "," , value } , ")" ;
anchor_expr = "at" , identifier , [ "in" , universal_expr ] , [ domain ] ;

    (* === CHECK EXPRESSIONS === *)
check_expr = "check_at" , identifier ;

    (* === PAIRWISE EXPRESSIONS === *)
symbolic_distance = "distance" , "(" , identifier , "," , identifier , "," , value , ")" ;

pairwise_expr = identifier , "~" , identifier , "with" , symbolic_distance ;

    (* === PROPERTY DEFINITION === *)
property_type = ? official_properties ? | ? uppercase_string ?;

property = "[" , property_type , "]" , ":" , NEWLINE , property_expr , "->" , assertion ;

property_section = property , [ abstractor ] ;

(* === SECTION DEFINITION === *)
section = { comments } , ( declaration_section | property_section ) ;

(* === ABSTRACTOR SECTION === *)
abstractor = "using" , ? official_backends? , [ "(" , { args } , ")" ] ;

(* === TARGET DECLARATION === *)
target_declaration = "target" , ":=" , identifier ;

(* === MODEL DECLARATION === *)
model = quoted_identifier ;

model_declaration = "model" , ":=" , model ;

(* === FULL PROGRAM === *)
header = { NEWLINES } , { comments } , { NEWLINES } , [ model_declaration ] , [ target_declaration ] ;

body = { NEWLINES } , section , { SEPARATOR , section } ;

footer = { comments | NEWLINES } ;

program = header , body , footer ;