%import common.WS
%import common.WS_INLINE
%import common.NEWLINE
%import common.ESCAPED_STRING
%import common.NUMBER
%import common.DIGIT
%ignore WS

CLASSIFICATION : "CLASSIFICATION"
REGRESSION : "REGRESSION"
CLUSTERING : "CLUSTERING"
ANOMALY_DETECTION : "ANOMALY_DETECTION"
REINFORCEMENT_LEARNING : "REINFORCEMENT_LEARNING"

ROBUTNESS : "ROBUTNESS"
STABILITY : "STABILITY"
FAIRNESS : "FAIRNESS"
MONOTONICITY : "MONOTONICITY"
BOUND : "BOUND"
LOGIC : "LOGIC"

# ===

# === BASIC CHARACTER DEFINITIONS ===
CHAR :  /(a-zA-Z)?/

# === BASIC VALUE TYPES ===
STRING :  ESCAPED_STRING 
true :  "True" | "true" 
false :  "False" | "false" 
boolean :  true | false 
identifier :  STRING ( STRING | DIGIT | "_" | ".")* 
value :  STRING | DIGIT | boolean 

# === ARGUMENT LIST AND VALUE ===
arg :  identifier "=" value 
args :  arg ( " " arg )* 


# === PARAMETER LIST AND VALUE ===
param :  identifier "=" value
params :  param (" " param )*

# === SEPARATOR DEFINITIONS ===
SEPARATOR :  NEWLINE | ";"

# === PROGRAM STRUCTURE ===
# === PROGRAM COMPONENTS ===

# === COMMENTS ===
simple_comment :  "#" /(^\n)?/ 
multiline_comment :  "'''" ( /'''(.|\n)*?'''/ )* "'''" 
comment :  simple_comment | multiline_comment 

# === DECLARATION SECTION ===
declaration_section :  identifier ":=" value SEPARATOR

# === PROPERTY SECTION ===
logic_term :  "AND" | "OR" 
comparison_op :  "==" | "!=" | "<" | "<=" | ">" | ">=" 
logic_condition :  ( "NOT" )? identifier comparison_op value 
logic_consequence :  ( "NOT" )? identifier comparison_op value 
logic_implication :  "(" logic_condition "->" logic_consequence ")" 
logic_assertion :  logic_implication ( logic_term logic_implication )* 


function :  /.*/ 
function_expr :  function "(" ( args )? ")" 
logic_expr :  CLASSIFICATION | REGRESSION | CLUSTERING | ANOMALY_DETECTION | REINFORCEMENT_LEARNING "." function_expr 

assertion :  logic_expr | logic_assertion 

# === PROPERTY EXPRESSION OPTIONS ===
property_expr :  quantifier_expr | anchor_expr | check_expr | pairwise_expr 
quantifier_set :  /.*/ 
quantifier_expr :  "forall" identifier "in" quantifier_set 

domain :  "with" identifier "(" value ( " " value )* ")" 
anchor_expr :  "at" identifier "in" ( quantifier_set | domain ) 

check_expr :  "check_at" identifier 

symbolic_distance :  "distance(" identifier " " identifier " " value ")" 
pairwise_expr :  identifier "~" identifier "with" symbolic_distance 

property_type :  ROBUTNESS | STABILITY | FAIRNESS | MONOTONICITY | BOUND | LOGIC | /(A-Z)?/
property :  "(" property_type ")?" ":" NEWLINE property_expr "->" assertion 
property_section :  ( comment )? property ( abstractor )? ( SEPARATOR )? 

section :  declaration_section | property_section 


# === ABSTRACTOR SECTION ===
abstractor :  "using" /.*/ ( "(" ( params )* ")" )? 

program :  ( comment | section | target_declaration )* 
