
official_problems = {
    "CLASSIFICATION" : '"CLASSIFICATION"',
    "REGRESSION" : '"REGRESSION"',
    "CLUSTERING" : '"CLUSTERING"',
    "ANOMALY_DETECTION" : '"ANOMALY_DETECTION"',
    "REINFORCEMENT_LEARNING" : '"REINFORCEMENT_LEARNING"',
}